/**
 * Synthesizes all 8 game sound effects and encodes them as small mono MP3s
 * (total well under 500 KB). The sounds are generated by this script, so they
 * are 100% royalty-free.
 *
 * Run from tools/: `npm run sounds`
 */
import fs from 'node:fs';
import path from 'node:path';
import lamejsModule from '@breezystack/lamejs';
import { fileURLToPath } from 'node:url';

const lamejs = /** @type {any} */ (lamejsModule);

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../mobile/assets/sounds');
const SR = 44100;

// ---------- helpers ----------------------------------------------------------
function synth(duration, fn) {
  const n = Math.floor(SR * duration);
  const out = new Float64Array(n);
  for (let i = 0; i < n; i++) out[i] = fn(i / SR, i / n);
  return out;
}

function normalize(buf, peak = 0.88) {
  let max = 0;
  for (const v of buf) max = Math.max(max, Math.abs(v));
  if (max === 0) return buf;
  const k = peak / max;
  for (let i = 0; i < buf.length; i++) buf[i] *= k;
  return buf;
}

function mix(...buffers) {
  const n = Math.max(...buffers.map((b) => b.length));
  const out = new Float64Array(n);
  for (const b of buffers) for (let i = 0; i < b.length; i++) out[i] += b[i];
  return out;
}

function delayed(buf, seconds) {
  const offset = Math.floor(seconds * SR);
  const out = new Float64Array(buf.length + offset);
  for (let i = 0; i < buf.length; i++) out[i + offset] = buf[i];
  return out;
}

function encodeMp3(name, samples) {
  const encoder = new lamejs.Mp3Encoder(1, SR, 96);
  const pcm = new Int16Array(samples.length);
  for (let i = 0; i < samples.length; i++) {
    const v = Math.max(-1, Math.min(1, samples[i]));
    pcm[i] = v < 0 ? v * 0x8000 : v * 0x7fff;
  }
  const chunks = [];
  const block = 1152;
  for (let i = 0; i < pcm.length; i += block) {
    const chunk = pcm.subarray(i, i + block);
    const encoded = encoder.encodeBuffer(chunk);
    if (encoded.length > 0) chunks.push(Buffer.from(encoded));
  }
  const tail = encoder.flush();
  if (tail.length > 0) chunks.push(Buffer.from(tail));
  const file = path.join(OUT, `${name}.mp3`);
  fs.writeFileSync(file, Buffer.concat(chunks));
  console.log(`  ${name}.mp3  ${(samples.length / SR).toFixed(2)}s  ${fs.statSync(file).size} bytes`);
}

// ---------- instruments -------------------------------------------------------
function bell(freq, dur, decay = 6) {
  return synth(dur, (t) => {
    const env = Math.exp(-t * decay);
    return (
      (Math.sin(2 * Math.PI * freq * t) + 0.35 * Math.sin(4 * Math.PI * freq * t)) * env
    );
  });
}

function brassNote(freq, dur) {
  return synth(dur, (t, p) => {
    const attack = Math.min(1, t / 0.02);
    const release = Math.min(1, (1 - p) / 0.12);
    const env = attack * release;
    return (
      (Math.sin(2 * Math.PI * freq * t) +
        0.35 * Math.sin(4 * Math.PI * freq * t) +
        0.18 * Math.sin(6 * Math.PI * freq * t)) *
      env *
      0.8
    );
  });
}

// ---------- sounds -------------------------------------------------------------
// 1) Soft button tap
const tap = synth(0.07, (t) => {
  const env = Math.exp(-t * 70);
  return (Math.sin(2 * Math.PI * 210 * t) + 0.35 * Math.sin(2 * Math.PI * 420 * t)) * env;
});

// 2) Bright chime (correct word): C6 -> E6 -> G6 arpeggio
const correct = mix(
  delayed(bell(1046.5, 0.3, 7), 0),
  delayed(bell(1318.5, 0.3, 7), 0.1),
  delayed(bell(1568.0, 0.42, 6), 0.2),
);

// 3) Gentle buzz (wrong selection): two close low sines beating
const wrong = synth(0.3, (t) => {
  const attack = Math.min(1, t / 0.015);
  const env = attack * Math.exp(-t * 9);
  return ((Math.sin(2 * Math.PI * 130 * t) + Math.sin(2 * Math.PI * 138 * t)) / 2) * env;
});

// 4) Victory fanfare (level complete): C5 E5 G5 C6 + chord
const fanfare = mix(
  delayed(brassNote(523.25, 0.14), 0),
  delayed(brassNote(659.25, 0.14), 0.13),
  delayed(brassNote(783.99, 0.14), 0.26),
  delayed(brassNote(1046.5, 0.16), 0.39),
  delayed(
    mix(brassNote(523.25, 0.8), brassNote(659.25, 0.8), brassNote(783.99, 0.8), brassNote(1046.5, 0.8)),
    0.55,
  ),
);

// 5) Subtle countdown tick
const tick = synth(0.045, (t) => {
  const env = Math.exp(-t * 160);
  return Math.sin(2 * Math.PI * 1900 * t) * env * 0.6;
});

// 6) Light swoosh (drag): filtered noise sweep
const swoosh = (() => {
  const dur = 0.24;
  let lp = 0;
  return synth(dur, (t, p) => {
    // white noise -> one-pole lowpass whose cutoff sweeps up
    const cutoff = 500 + 5500 * p * p;
    const a = Math.exp((-2 * Math.PI * cutoff) / SR);
    const noise = Math.random() * 2 - 1;
    lp = (1 - a) * noise + a * lp;
    const env = Math.pow(Math.sin(Math.PI * p), 1.4);
    return lp * env;
  });
})();

// 7) Coin collect sparkle (bonus word): B5 ping -> E6 ping
const coin = mix(delayed(bell(987.77, 0.12, 9), 0), delayed(bell(1318.5, 0.4, 6), 0.07));

// 8) Descending tone (game over): E4 -> D4 -> C4
const gameover = mix(
  delayed(brassNote(329.63, 0.3), 0),
  delayed(brassNote(293.66, 0.3), 0.28),
  delayed(mix(brassNote(261.63, 0.65), brassNote(130.81, 0.65)), 0.56),
);

// ---------- encode ---------------------------------------------------------------
fs.mkdirSync(OUT, { recursive: true });
encodeMp3('tap', normalize(tap, 0.7));
encodeMp3('correct', normalize(correct));
encodeMp3('wrong', normalize(wrong, 0.65));
encodeMp3('fanfare', normalize(fanfare));
encodeMp3('tick', normalize(tick, 0.5));
encodeMp3('swoosh', normalize(swoosh, 0.5));
encodeMp3('coin', normalize(coin));
encodeMp3('gameover', normalize(gameover, 0.8));

const total = fs.readdirSync(OUT).reduce((sum, f) => sum + fs.statSync(path.join(OUT, f)).size, 0);
console.log(`Total: ${(total / 1024).toFixed(1)} KB (budget: 500 KB)`);
console.log('Sounds generated ✔');
